---
- name: Deploy Apache Web Server
  hosts: web_servers
  become: yes
  vars_files:
    - ../vars/apache_version.yml
  tasks:
    - name: Install Apache
      yum:
        name: "httpd-{{ latest_version }}"
        state: present

    - name: Start Apache Service
      service:
        name: httpd
        state: started
